"use client";
import React, { forwardRef } from 'react';
import { Trophy, Target, Hash, Flame } from 'lucide-react';

// 16:9 Aspect Ratio Card for Download
const PerformanceCard = forwardRef(({ user, userData }, ref) => {
    const stats = userData?.stats || { totalQuizzes: 0, totalQuestions: 0, totalScore: 0 };
    const winRate = stats.totalQuestions > 0 ? Math.round((stats.totalScore / stats.totalQuestions) * 100) : 0;
    
    // Find best category
    let bestCat = "General";
    let maxVal = -1;
    if(userData?.stats?.categoryWins) {
        Object.entries(userData.stats.categoryWins).forEach(([cat, count]) => {
            if(count > maxVal) { maxVal = count; bestCat = cat; }
        });
    }

    return (
        <div ref={ref} className="bg-[#020617] p-4 w-[800px] h-[450px] flex items-center justify-center">
            <div className="relative w-full h-full rounded-2xl overflow-hidden border border-white/20 bg-slate-900 flex">
                {/* Visual Side */}
                <div className="w-1/3 bg-gradient-to-br from-orange-600 to-red-900 flex flex-col items-center justify-center p-8 text-center relative overflow-hidden">
                    <div className="w-24 h-24 rounded-full bg-white/10 border-2 border-white/30 flex items-center justify-center mb-4 text-4xl font-bold text-white shadow-xl backdrop-blur-sm">
                        {userData?.displayName?.[0]?.toUpperCase() || "U"}
                    </div>
                    <h2 className="text-2xl font-bold text-white mb-1 truncate w-full">{userData?.displayName || "Player"}</h2>
                    <p className="text-orange-200 text-sm">Flames Challenger</p>
                </div>

                {/* Stats Side */}
                <div className="w-2/3 p-8 flex flex-col justify-between">
                    <div className="flex justify-between items-start">
                        <h1 className="text-3xl font-black text-white tracking-tight">PERFORMANCE <span className="text-orange-500">CARD</span></h1>
                        <Trophy className="text-yellow-500" size={32}/>
                    </div>

                    <div className="grid grid-cols-3 gap-4">
                        <div className="bg-white/5 rounded-xl p-4 border border-white/10">
                            <Target className="text-blue-400 mb-2" size={20}/>
                            <div className="text-2xl font-bold text-white">{winRate}%</div>
                            <div className="text-[10px] text-slate-400 uppercase tracking-widest">Accuracy</div>
                        </div>
                        <div className="bg-white/5 rounded-xl p-4 border border-white/10">
                            <Hash className="text-green-400 mb-2" size={20}/>
                            <div className="text-2xl font-bold text-white">{stats.totalQuizzes}</div>
                            <div className="text-[10px] text-slate-400 uppercase tracking-widest">Quizzes</div>
                        </div>
                        <div className="bg-white/5 rounded-xl p-4 border border-white/10">
                            <Flame className="text-orange-400 mb-2" size={20}/>
                            <div className="text-xl font-bold text-white truncate">{bestCat}</div>
                            <div className="text-[10px] text-slate-400 uppercase tracking-widest">Best Skill</div>
                        </div>
                    </div>

                    <div className="text-right text-xs text-slate-600 mt-4 border-t border-white/5 pt-2">
                        Generated by Flames Quiz • ignite.your.mind
                    </div>
                </div>
            </div>
        </div>
    );
});

PerformanceCard.displayName = "PerformanceCard";
export default PerformanceCard;