"use client";
import React, { useRef, useState } from 'react';
import { toPng } from 'html-to-image';
import { Trophy, Download, Home } from 'lucide-react';
import { GlassCard, Button } from './ui/Shared';

const formatTime = (seconds) => {
    if (!seconds) return "--"; 
    const h = Math.floor(seconds / 3600); const m = Math.floor((seconds % 3600) / 60); const s = seconds % 60;
    const parts = []; if (h > 0) parts.push(`${h}h`); if (m > 0) parts.push(`${m}m`); parts.push(`${s}s`); return parts.join(' ');
};

export default function ResultView({ result, onHome }) {
    const resultRef = useRef(null);
    const [isSaving, setIsSaving] = useState(false);

    const handleSaveImage = async () => {
        if (!resultRef.current) return;
        setIsSaving(true);
        setTimeout(async () => {
            try {
                const dataUrl = await toPng(resultRef.current, { cacheBust: true, backgroundColor: '#020617' });
                const link = document.createElement('a');
                link.download = `Flames_${result.playerName.replace(/\s+/g, '_')}_Result.png`;
                link.href = dataUrl;
                link.click();
                setIsSaving(false);
            } catch (err) { 
                console.error("Image gen error", err); 
                setIsSaving(false); 
                alert("Error generating image."); 
            }
        }, 100);
    };

    let gradeColor = "text-red-500", gradeText = "LOW", bgGradient = "from-red-500/20 to-orange-500/5", trophyColor = "text-red-400";
    if (result.accuracy >= 70) { gradeColor = "text-cyan-400"; gradeText = "ACE"; bgGradient = "from-cyan-500/20 to-blue-500/5"; trophyColor = "text-cyan-400"; }
    else if (result.accuracy >= 50) { gradeColor = "text-yellow-400"; gradeText = "MID"; bgGradient = "from-yellow-500/20 to-orange-500/5"; trophyColor = "text-yellow-400"; }

    return (
        <div className="max-w-2xl mx-auto w-full animate-slide-up pb-10">
            <div ref={resultRef} className="rounded-2xl overflow-hidden bg-[#020617] p-2"> 
                <GlassCard className={`text-center p-12 mb-6 border-t-4 ${result.accuracy >= 70 ? 'border-t-cyan-500' : result.accuracy >= 50 ? 'border-t-yellow-500' : 'border-t-red-500'} print:border print:shadow-none`}>
                    <div className={`absolute top-0 left-0 w-full h-32 bg-gradient-to-b ${bgGradient} blur-3xl -z-10`}></div>
                    <div className="mb-6 inline-block p-6 rounded-full bg-slate-900/50 border border-white/10">
                        <Trophy size={64} className={`${trophyColor} drop-shadow-[0_0_15px_rgba(255,255,255,0.2)]`} />
                    </div>
                    <h2 className="text-5xl font-black mb-2 uppercase tracking-tight text-slate-100">{result.playerName}</h2>
                    <div className="inline-block px-4 py-1 rounded-full bg-white/5 border border-white/10 text-slate-300 mb-8">{result.quizTitle}</div>
                    <div className="grid grid-cols-3 gap-4 mb-8">
                        <div className="p-4 rounded-xl bg-slate-950/50 border border-white/10 flex flex-col items-center justify-center">
                            <div className="text-xl md:text-2xl font-bold text-white">{result.score}/{result.totalQuestions}</div>
                            <div className="text-xs text-slate-500 uppercase tracking-widest mt-1">Score</div>
                        </div>
                        <div className="p-4 rounded-xl bg-slate-950/50 border border-white/10 flex flex-col items-center justify-center">
                            <div className={`text-xl md:text-2xl font-bold ${gradeColor}`}>{result.accuracy}%</div>
                            <div className="text-xs text-slate-500 uppercase tracking-widest mt-1">{gradeText}</div>
                        </div>
                        <div className="p-4 rounded-xl bg-slate-950/50 border border-white/10 flex flex-col items-center justify-center">
                            <div className="text-xl md:text-2xl font-bold text-blue-400">{formatTime(result.timeSpent)}</div>
                            <div className="text-xs text-slate-500 uppercase tracking-widest mt-1">Time</div>
                        </div>
                    </div>
                    <div className="flex flex-wrap justify-center gap-2 mb-8">
                        {Object.keys(result.stats).map((qId, idx) => {
                            const stat = result.stats[qId];
                            return <div key={qId} className={`w-3 h-3 rounded-full ${stat.correct ? 'bg-green-500' : stat.answered === 'skipped' ? 'bg-slate-600' : 'bg-red-500'}`}></div>;
                        })}
                    </div>
                    <div className="text-xs text-slate-600">Generated by Flames Quiz</div>
                </GlassCard>
            </div>
            <div className="flex gap-4 justify-center mt-6">
                <Button variant="secondary" onClick={handleSaveImage} disabled={isSaving}>
                    {isSaving ? "Capturing..." : <><Download size={18} /> Save Result</>}
                </Button>
                <Button onClick={onHome}><Home size={18} /> Home</Button>
            </div>
        </div>
    );
}